### ISSUE TITLE
python client is broken against dev code in some cases (old sessions?)

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2090]
There's some sort of transition problem involving the change to logins, the cutover, existing sessions, and the python client.

I was able to get this error message using a script that works against the prod site:
```python
$ ./w game_info dev 1
could not parse return:
Notice: Undefined index: stay_logged_in in /var/www/api/api_core.php on line 99
{"data":{"userName":"glassonion"},"message":null,"status":"ok"}
Traceback (most recent call last):
  File "/Users/chaos/src/git/buttonmen-dev/buttonmen-dev/tools/api-client/python/game_info", line 44, in <module>
    if not b.verify_login():
  File "/Users/chaos/src/git/buttonmen-dev/buttonmen-dev/tools/api-client/python/lib/bmapi.py", line 88, in verify_login
    if retval.status == 'ok':
AttributeError: 'bool' object has no attribute 'status'
```

But then i ran `b.login()`, and since i did that, everything works fine.

**Comment by cgolubi1** [comment]
Okay, in fact, i'm seeing this in the logs when i load the website via the browser:
```
[Wed Jul 27 11:10:26 2016] [error] [client X.X.X.X] PHP Notice:  Undefined index: stay_logged_in in /var/www/api/api_core.php on line 99
```

So obviously something ain't right.

**Comment by cgolubi1** [comment]
Yeah, this is the problem, in `api_core.php`:
```php
        if (count($resultArray) == 1) {
            update_session($auth_userid, $resultArray[0]['name_ingame']);
            set_authorisation_cookies($auth_userid, $auth_key, (bool)$_COOKIE['stay_logged_in']);
            return TRUE;
        }
```

It has to be legal for the cookie not to have `stay_logged_in` set, because older cookies won't.  Well, this is why we have a dev site.  :>)

Shadowshade, can you put in a fix making that parameter optional, or should i?

**Comment by cgolubi1** [comment]
I'll go ahead and put in the fix for this.
