### ISSUE TITLE
need to fix replay_loop to work with multiple responderTest files

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2386]
Splitting responderTest.php into multiple files broke replay_loop's expectations about being able to find and modify that file:

```
ip-172-31-47-11,[~],11:56(0)$ ./replay_loop -a
wc: /buttonmen/test/src/api/responderTest.php: No such file or directory
Traceback (most recent call last):
  File "./replay_loop", line 160, in <module>
    setup()
  File "./replay_loop", line 55, in setup
    testlines = int(subprocess.check_output(['wc', '-l', TESTFILE]).split()[0])
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['wc', '-l', '/buttonmen/test/src/api/responderTest.php']' returned non-zero exit status 1
ip-172-31-47-11,[~],11:56(1)$ 
```

Fix that.

**Comment by cgolubi1** [comment]
Mind you, the new responderTest structure should actually let us do something *less* hackish.  It's just a question of doing it.
