### ISSUE TITLE
players can't set passwords

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2418]
If you browse to http://www.buttonweavers.com/ui/prefs.html, enter current/new passwords in the box, and click "Save preferences", you get an internal error.  The apache error log looks like this:

```
[Thu Nov 22 16:17:50.045340 2018] [:error] [pid 22165] [client 10.0.2.2:52436] PHP Fatal error:  Uncaught Error: Call to undefined function password_hashed() in /var/www/engine/BMInterfacePlayer.php:184
Stack trace:
#0 /var/www/engine/BMInterfacePlayer.php(150): BMInterfacePlayer->password_hashed_universal('c11')
#1 /var/www/api/ApiResponder.php(461): BMInterfacePlayer->set_player_info(1, Array, Array)
#2 /var/www/api/ApiResponder.php(950): ApiResponder->get_interface_response_savePlayerInfo(Object(BMInterface), Array)
#3 /var/www/api/responder.php(21): ApiResponder->process_request(Array)
#4 {main}
  thrown in /var/www/engine/BMInterfacePlayer.php on line 184, referer: http://localhost:8080/ui/prefs.html
```

**Comment by cgolubi1** [comment]
It's a trivial typo; i have a fix.  I'm going to take a minute to:
* See whether i can easily make a regression test that would have caught this
* Figure out what player triggered this (i discovered it because of a log entry, obviously not the one in the description, which was my test user), because i suspect it may have botched that player's live password entry on the site, so we may need to reach out to them and/or fix their entry

**Comment by cgolubi1** [comment]
Okay, i think this is important but not so time-critical i can't eat Thanksgiving dinner.  `:>)`  I'll definitely have a PR in today; i think i have the unit test ready.

**Comment by cgolubi1** [comment]
Cool.  With the new test but without the code fix:

```
There was 1 error:

1) responder00Test::test_request_savePlayerInfo
Error: Call to undefined function password_hashed()

/buttonmen/src/engine/BMInterfacePlayer.php:184
/buttonmen/src/engine/BMInterfacePlayer.php:150
/buttonmen/src/api/ApiResponder.php:461
/buttonmen/src/api/ApiResponder.php:950
/buttonmen/test/src/api/responderTestFramework.php:912
/buttonmen/test/src/api/responder00Test.php:186
```

**Comment by cgolubi1** [comment]
Shadowshade: i'll follow up via e-mail about the impacted player.
