### ISSUE TITLE
action log regression when a game ends in a draw

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2734]
From routine replay testing:

```
Starting game 14
could not parse return: <br />
<b>Notice</b>:  Undefined variable: sqlParameters in <b>/var/www/engine/BMInterfaceGameAction.php</b> on line <b>173</b><br />
{"data":{"gameId":14,"gameState":"START_TURN","activePlayerIdx":0,"playerWithInitiativeIdx":0,"roundNumber":4,"maxWins":3,"description":"","previousGameId":null,"validAttackTypeArray":["Power","Skill"],"gameSkillsInfo":{"Mood":{"code":"?","description":"These are a subcategory of Swing dice, whose size changes randomly when rerolled. At the very start of the game (and again after any round they lose, just as with normal Swing dice) the player sets the initial size of Mood Swing dice, but from then on whenever they are rolled their size is set randomly to that of a \"real-world\" die (i.e. 1, 2, 4, 6, 8, 10, 12, 20, or 30 sides) within the range allowable for that Swing type.","interacts":{"Ornery":"Dice with both Ornery and Mood Swing have their sizes randomized during ornery rerolls"}},"Ornery":{"code":"o","description":"Ornery dice reroll every time the player makes any attack - whether the Ornery dice participated in it or not. The only time they don't reroll is if the player passes, making no attack whatsoever.","interacts":{"Mood":"Dice with both Ornery and Mood Swing have their sizes randomized during ornery rerolls"}},"Reserve":{"code":"r","description":"These are extra dice which may be brought into play part way through a game. Each time you lose a round you may choose another of your Reserve Dice; it will then be in play for all future rounds.","interacts":[]}},"playerDataArray":[{"playerId":3,"button":{"name":"Kiyone","recipe":"(4) (4) (10) (12) (6) r(10) r(10) r(20)","originalRecipe":"(4) (4) (10) (12) r(6) r(10) r(10) r(20)","artFilename":"kiyone.png"},"activeDieArray":[{"value":3,"sides":4,"skills":[],"properties":[],"recipe":"(4)","description":"4-sided die"},{"value":2,"sides":4,"skills":[],"properties":[],"recipe":"(4)","description":"4-sided die"},{"value":6,"sides":10,"skills":[],"properties":[],"recipe":"(10)","description":"10-sided die"},{"value":1,"sides":12,"skills":[],"properties":[],"recipe":"(12)","description":"12-sided die"},{"value":1,"sides":6,"skills":[],"properties":[],"recipe":"(6)","description":"6-sided die"}],"capturedDieArray":[],"outOfPlayDieArray":[],"swingRequestArray":[],"optRequestArray":[],"prevSwingValueArray":[],"prevOptValueArray":[],"turboSizeArray":[],"waitingOnAction":true,"roundScore":18,"sideScore":-9,"gameScoreArray":{"W":0,"L":2,"D":1},"lastActionTime":1624316673,"hasDismissedGame":false,"canStillWin":null,"playerName":"responder003","isOnVacation":false,"isChatPrivate":false,"playerColor":"#dd99dd"},{"playerId":5,"button":{"name":"Skeeve","recipe":"o(V)? o(W)? o(X)? o(Y)? o(Z)?","originalRecipe":"o(V)? o(W)? o(X)? o(Y)? o(Z)?","artFilename":"skeeve.png"},"activeDieArray":[{"value":1,"sides":12,"skills":["Ornery","Mood"],"properties":[],"recipe":"o(V)?","description":"Ornery V Mood Swing Die (with 12 sides)"},{"value":2,"sides":7,"skills":["Ornery","Mood"],"properties":[],"recipe":"o(W)?","description":"Ornery W Mood Swing Die (with 7 sides)"},{"value":11,"sides":15,"skills":["Ornery","Mood"],"properties":[],"recipe":"o(X)?","description":"Ornery X Mood Swing Die (with 15 sides)"},{"value":17,"sides":17,"skills":["Ornery","Mood"],"properties":[],"recipe":"o(Y)?","description":"Ornery Y Mood Swing Die (with 17 sides)"},{"value":5,"sides":12,"skills":["Ornery","Mood"],"properties":[],"recipe":"o(Z)?","description":"Ornery Z Mood Swing Die (with 12 sides)"}],"capturedDieArray":[],"outOfPlayDieArray":[],"swingRequestArray":[],"optRequestArray":[],"prevSwingValueArray":[],"prevOptValueArray":[],"turboSizeArray":[],"waitingOnAction":false,"roundScore":31.5,"sideScore":9,"gameScoreArray":{"W":2,"L":0,"D":1},"lastActionTime":1624316674,"hasDismissedGame":false,"canStillWin":null,"playerName":"responder004","isOnVacation":false,"isChatPrivate":false,"playerColor":"#ddffdd"}],"creatorDataArray":{"creatorId":3,"creatorName":"responder003"},"dieBackgroundType":"realistic","currentPlayerIdx":0,"gameActionLog":[{"timestamp":1624316674,"player":"","message":"responder003 won initiative for round 4. Initial die values: responder003 rolled [(4):3, (4):2, (10):6, (12):1, (6):1], responder004 rolled [o(V=12)?:1, o(W=7)?:2, o(X=15)?:11, o(Y=17)?:17, o(Z=12)?:5]."},{"timestamp":1624316674,"player":"responder004","message":"responder004 performed Power attack using [o(W=6)?:2] against [(4):1]; Defender (4) was captured; Attacker o(W=6)? changed size from 6 to 4 sides, recipe changed from o(W=6)? to o(W=4)?, rerolled 2 => 3"},{"timestamp":1624316673,"player":"responder003","message":"responder003 passed"},{"timestamp":1624316673,"player":"responder004","message":"responder004 performed Power attack using [o(W=6)?:5] against [(4):3]; Defender (4) was captured; Attacker o(W=6)? remained the same size, recipe remained o(W=6)?, rerolled 5 => 2"},{"timestamp":1624316673,"player":"responder003","message":"responder003 performed Power attack using [(4):4] against [o(Y=6)?:1]; Defender o(Y=6)? was captured; Attacker (4) rerolled 4 => 1"},{"timestamp":1624316672,"player":"responder004","message":"responder004's idle ornery dice rerolled at end of turn: o(W=10)? changed size from 10 to 6 sides, recipe changed from o(W=10)? to o(W=6)?, rerolled 8 => 5"},{"timestamp":1624316672,"player":"responder004","message":"responder004 performed Power attack using [o(Y=10)?:10] against [(10):2]; Defender (10) was captured; Attacker o(Y=10)? changed size from 10 to 6 sides, recipe changed from o(Y=10)? to o(Y=6)?, rerolled 10 => 1"},{"timestamp":1624316671,"player":"responder003","message":"responder003 performed Skill attack using [(4):3,(4):2,(10):1] against [o(V=8)?:6]; Defender o(V=8)? was captured; Attacker (4) rerolled 3 => 3; Attacker (4) rerolled 2 => 4; Attacker (10) rerolled 1 => 2"},{"timestamp":1624316670,"player":"responder004","message":"responder004's idle ornery dice rerolled at end of turn: o(W=10)? remained the same size, recipe remained o(W=10)?, rerolled 1 => 8; o(Y=20)? changed size from 20 to 10 sides, recipe changed from o(Y=20)? to o(Y=10)?, rerolled 3 => 10"},{"timestamp":1624316670,"player":"responder004","message":"responder004 performed Power attack using [o(V=12)?:4] against [(12):2]; Defender (12) was captured; Attacker o(V=12)? changed size from 12 to 8 sides, recipe changed from o(V=12)? to o(V=8)?, rerolled 4 => 6"}],"gameActionLogCount":47,"gameChatLog":[],"gameChatLogCount":0,"timestamp":1624316674,"gameChatEditable":false},"message":"Internal error while reading log entries","status":"ok","BM_RAND_VALS_ROLLED":null,"BM_SKILL_RAND_VALS_ROLLED":null}
Traceback (most recent call last):
  File "./test_log_games", line 71, in <module>
    c.log_test_game(i, button1, button2)
  File "lib/random_ai.py", line 1777, in log_test_game
    self.next_game_action()
  File "lib/random_ai.py", line 1761, in next_game_action
    if state == 'START_TURN': self._game_action_start_turn()
  File "lib/random_ai.py", line 1648, in _game_action_start_turn
    self.loaded_data['playerDataArray'][0])
  File "lib/random_ai.py", line 1571, in _game_action_start_turn_player
    self.record_load_game_data()
  File "lib/random_ai.py", line 1737, in record_load_game_data
    self.game_id))
  File "lib/random_ai.py", line 1657, in bug
    raise ValueError, message
ValueError: load_game_data(14) unexpectedly returned False
$ 
```

**Comment by cgolubi1** [comment]
This is a trivial regression from the action log stuff.  Let me make sure to add an action log load test that exercises the `end_draw` case.

**Comment by cgolubi1** [comment]
Specifically: the coverage gap isn't in BMGameAction itself --- we have an `end_draw` test --- it's in BMInterfaceGameAction, which is only exercised by responder tests.  I maintain what i said in the PR, namely that we don't have that many distinct action log types, and if there's one which isn't exercised by any responder test, that's a problem in itself.  So i'm going to see how easy it would be to make one of the existing responder tests play a round to a draw.

**Comment by cgolubi1** [comment]
Okay, that fix should take care of this issue.  I think based on a grep that it's the only copy/paste-o of this type, but regardless i found it via garden-variety replay testing on master, so i'll update that and i should find out whether i did anything else similar in short order.
