### ISSUE TITLE
replay testing sometimes fails because mysqld gets OOM-killed

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#2801]
Sometimes replay testing fails because mysqld gets OOM-killed.  The log signature of this particular issue is:
* When `replay-cgolubi1-master` is recording novel game N (the actual problem game), it succeeds, but mysqld crashes at the very *end* of recording the game, with an OOM
* So when the loop goes to record game N+1, mysqld isn't back yet, and creation of game N+1 fails, so the replay records that it *expects* that game to fail
* The replay of game N+1 fails with a signature like:
```
1) responder99Test::test_interface_game_00094
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Internal error'
+'Game create failed: Called bm_rand() from a test requiring overrides, but
+BM_RAND_VALS is empty'
```

There are two problems here:
1. games cause mysqld to be OOM-killed (an actual buttonmen problem)
2. the test rig records a confusing signature when this happens

I reserve the right to use this issue as the reference for addressing either of those at my discretion --- obviously the first one is more interesting because it's an actual game problem.

**Comment by cgolubi1** [comment]
I primarily cut this issue because i wanted a place to record signatures of games that cause OOM.  Obviously, this is related to the various hit table issues, but recording a list of OOM games on those issues or fixes didn't seem quite correct.

| Replay file containing failure | Game failing create | OOM game | Matchup |
|---|---|---|---|
| 651755bfb6a62e17fed23e95549018327558fa13.games.20220103.175803 | 00094 | 00093 | IIConfused vs IIConfused |

**Comment by cgolubi1** [comment]
That said: it's not a good thing that replay_loop just rolls through game creation failing.  I added that functionality as part of CustomBM, because sometimes the CustomBM matchups are invalid.  But at the very least, we shouldn't expect create-time failures on any games *other* than CustomBM games.  And we definitely shouldn't expect internal errors on game creation.

**Comment by cgolubi1** [comment]
So replay testing fell over because of this signature:

```
Starting game 38
could not parse return: <head/><br/>
<b>Fatal error</b>:  Uncaught PDOException: Database connection failed in /var/www/database/mysql.inc.php:63
Stack trace:
#0 /var/www/api/api_core.php(125): conn()
#1 /var/www/api/ApiResponder.php(1082): auth_session_exists()
#2 /var/www/api/ApiResponder.php(998): ApiResponder-&gt;verify_function_access(Array)
#3 /var/www/api/responder.php(23): ApiResponder-&gt;process_request(Array)
#4 {main}
  thrown in <b>/var/www/database/mysql.inc.php</b> on line <b>63</b><br/>

Traceback (most recent call last):
  File "./test_log_games", line 71, in <module>
    c.log_test_game(i, button1, button2)
  File "lib/random_ai.py", line 1819, in log_test_game
    self.record_create_game(button1, button2, use_prev_game=use_prev_game)
  File "lib/random_ai.py", line 1727, in record_create_game
    retval and retval.message or "NULL"))
  File "lib/random_ai.py", line 1697, in bug
    raise ValueError, message
ValueError: create_game(Jesse, Jasyeman, 3, custom_recipe_array=[]) unexpectedly gave invalid response: NULL
```

I think i don't want that --- i want `replay_loop` to record a BUG event when `create_game()` returns NULL.

(The root cause in this case was mysqld being OOM-killed during a IIconfused vs IIconfused matchup, which is a known issue.)

**Comment by cgolubi1** [comment]
Same thing happened again, so that's frequent enough that it's worth recording the BUG event.  Incidentally, the game that caused the OOM-kill this time was Dead Guy vs Skomp, which is a new one afair.  Does mysqld now get OOM-killed when *any* game goes to max rounds?

**Comment by cgolubi1** [comment]
I had a pretty mysterious OOM crash today, on replay (as in, while the site was replaying a game it had played before, not while playing novel games), and without any obviously pathological games --- the crashing game was Tonase vs Oregon, the last thing that happened before mysql hung afaict was this extremely normal-looking attack:

```
responder003 performed Skill attack using [(4):1,f(X=13):5] against [(R=6):6]; Defender (R=6) was captured; Attacker (4) rerolled 1 => 1; Attacker f(X=13) rerolled 5 => 6
```

and the game before the one that crashed was a Da Pimp vs Bush game that went 4 rounds, and i don't see any long-running or pathological games in the whole replay session.  So... nothing i can report.  Could be evidence that i'm currently running replays on a bad instance, or that the write-heavy workload of replay testing is abusive to mysql in a way that manifests in hangs.

Anyway, i turned on the slow query log and started things running again.  Just recording where i am for the record --- if there's a pattern of OOM-kills in the absence of a pathological game, it'd be worth slowing down replay-testing to fix it, so that i don't have to deal with crashes that aren't reflective of a bug or site-impacting problem.

**Comment by cgolubi1** [comment]
Just an update --- i got sick of mysterious OOMs and rebuilt the primary replay site on 2022-09-21, and i haven't had an OOM since then.  So, fine: sometimes bad hardware is bad, and isn't reflective of a site logic bug.  I'll continue to monitor.
